# Generated by Django 3.2 on 2022-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='won_by',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
