# Generated by Django 3.2 on 2022-03-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_desc', models.CharField(max_length=300)),
                ('commentor', models.CharField(max_length=64)),
                ('commented_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='auctions.listing')),
            ],
        ),
    ]
