# Generated by Django 3.2 on 2022-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
