# Generated by Django 3.2 on 2022-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_commentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='household', max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_desc',
            field=models.CharField(default='no comment', max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='won_by',
            field=models.CharField(default='', max_length=64),
        ),
    ]
